version: '3.3'
services:
  # The grafana container uses the image resulting from the build
  # of `./grafana` which simply packs some configuration into the
  # form of an image.
  #
  # This could instead be a volume-mounted container.
  grafana:
    build:
      context: grafana
      dockerfile: Dockerfile
      args:
        GRAFANA_TAG: grafana:7.2.1-ubuntu
    container_name: grafana
    ports:
      - '3000:3000'
    image: 'grafana/grafana:7.2.1-ubuntu'
    depends_on:
      - "nodejs_to_influxdb"
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    build:
      context: influxdb
      dockerfile: Dockerfile
      args:
        INFLUXDB_TAG: influxdb:1.8.3
    image: "influxdb"
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory
      - ./influxdb:/var/lib/influxdb
      # Mount for influxdb configuration
      #- config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      #- "8082:8082"
      # UDP Port
      #- "8089:8089/udp"
  nodejs_to_influxdb:
    build:
      context: nodejs_to_influxdb
      dockerfile: Dockerfile
    image: "nodejs_to_influxdb"
    container_name: nodejs_to_influxdb
    ports:
      - 4000:4000
    depends_on:
      - "influxdb"
