apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 1
datasources:
- orgId: 1
  version: 1
  name: InfluxDB-docker
  type: influxdb
  access: proxy
  url: http://influxdb:8086/
  database: co2
  isDefault: true
